[workspace]
authors = ["sontung <>"]
channels = ["pytorch", "rapidsai", "conda-forge", "nvidia"]
name = "env_pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
simple = "echo This is a simple task"

[dependencies]
python = "3.10.*"
pytorch = "2.5.1.*"
torchvision = "0.20.1.*"
pytorch-cuda = "12.4.*"
cuml = "25.02.*"
h5py = "*"
pykdtree = "*"
poselib = "*"
scikit-learn = "*"
pip = ">=25.1.1,<26"
pytorch-lightning = ">=2.5.2,<3"
pytorch-metric-learning = ">=2.8.1,<3"
prettytable = ">=3.16.0,<4"

[pypi-dependencies]
opencv-python = "*"
kornia = "*"
open3d = "*"
pycolmap = "*"
