[workspace]
authors = ["sontung <>"]
channels = ["rapidsai", "https://prefix.dev/conda-forge"]
name = "env_pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.0"

[dependencies]
pytorch-gpu = "*"
pycolmap = ">=0.3.0,<0.4"
h5py = ">=3.8.0,<4"
pykdtree = ">=1.4.2,<2"
poselib = ">=2.0.4,<3"
scikit-learn = ">=1.7.0,<2"
pytorch-lightning = ">=2.0.9,<3"
pytorch-metric-learning = ">=2.8.1,<3"
prettytable = ">=3.16.0,<4"
hloc = ">=1.4,<2"
cuml = "25.02.*"
python = "3.10.*"
pip = ">=25.1.1,<26"

[pypi-dependencies]
kornia = "*"
faiss-gpu = "*"
opencv-python = "*"
open3d = "*"

